# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created.
# For Tagging, it is using DEFAULT_BUMP as minor and hence create Minor release tags.
# Please refer to Workflow-ReadMe.txt file for the detailed description of this workflow.
# Also, added few points to Workflow-ReadMe.txt for future updations to this flow.

 
name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  BuildAndPublish:
    environment: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Generate tags No tagging
      uses: anothrNick/github-tag-action@1.36.0
      id: tagging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
        DEFAULT_BUMP: ${{ secrets.RELEASETYPE }}
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: update Tag for packaging
      run: |
            echo "Updating tag for published package to ${{ steps.tagging.outputs.new_tag }}"
            mvn versions:set -DnewVersion=${{ steps.tagging.outputs.new_tag }} -DprocessAllModules
            mvn versions:commit -DprocessAllModules   
            
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    outputs:
        CurrentTagVersion: ${{ steps.tagging.outputs.new_tag }}
        
  Release: 
     needs: BuildAndPublish
     environment: Release
     runs-on: ubuntu-latest
     permissions:
      contents: read
      packages: write
      
     steps:
     
     - uses: actions/checkout@v2
     
     - name: Create Release
       uses: elgohr/Github-Release-Action@master
       env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
       with:
        args: Release ${{ needs.BuildAndPublish.outputs.CurrentTagVersion }}
        
     - name: Push Updated tag from saved value
       uses: anothrNick/github-tag-action@1.36.0
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        CUSTOM_TAG: ${{ needs.BuildAndPublish.outputs.CurrentTagVersion }}
 
